// Code generated by "stringer -type=NodeType -output zz_generated.nodetype_string.go"; DO NOT EDIT.

package dslshape

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeTypeError-0]
	_ = x[NodeTypeFile-1]
	_ = x[NodeTypeComment-2]
	_ = x[NodeTypeUseFlag-3]
	_ = x[NodeTypeDefinition-4]
	_ = x[NodeTypeCaveatDefinition-5]
	_ = x[NodeTypeCaveatParameter-6]
	_ = x[NodeTypeCaveatExpression-7]
	_ = x[NodeTypeRelation-8]
	_ = x[NodeTypePermission-9]
	_ = x[NodeTypeTypeAnnotation-10]
	_ = x[NodeTypeTypeReference-11]
	_ = x[NodeTypeSpecificTypeReference-12]
	_ = x[NodeTypeCaveatReference-13]
	_ = x[NodeTypeTraitReference-14]
	_ = x[NodeTypeUnionExpression-15]
	_ = x[NodeTypeIntersectExpression-16]
	_ = x[NodeTypeExclusionExpression-17]
	_ = x[NodeTypeArrowExpression-18]
	_ = x[NodeTypeIdentifier-19]
	_ = x[NodeTypeNilExpression-20]
	_ = x[NodeTypeCaveatTypeReference-21]
}

const _NodeType_name = "NodeTypeErrorNodeTypeFileNodeTypeCommentNodeTypeUseFlagNodeTypeDefinitionNodeTypeCaveatDefinitionNodeTypeCaveatParameterNodeTypeCaveatExpressionNodeTypeRelationNodeTypePermissionNodeTypeTypeAnnotationNodeTypeTypeReferenceNodeTypeSpecificTypeReferenceNodeTypeCaveatReferenceNodeTypeTraitReferenceNodeTypeUnionExpressionNodeTypeIntersectExpressionNodeTypeExclusionExpressionNodeTypeArrowExpressionNodeTypeIdentifierNodeTypeNilExpressionNodeTypeCaveatTypeReference"

var _NodeType_index = [...]uint16{0, 13, 25, 40, 55, 73, 97, 120, 144, 160, 178, 200, 221, 250, 273, 295, 318, 345, 372, 395, 413, 434, 461}

func (i NodeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeType_index)-1 {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[idx]:_NodeType_index[idx+1]]
}
