---
schema: |+
  definition maineparnisari/user {}

  caveat maineparnisari/only_on_tuesday(day_of_week string) {
    day_of_week == 'tuesday'
  }

  definition maineparnisari/document {
  	relation writer: maineparnisari/user
  	relation reader: maineparnisari/user with maineparnisari/only_on_tuesday
    permission write = writer
    permission view = reader + write
  }

relationships: |
  maineparnisari/document:1#reader@maineparnisari/user:1[maineparnisari/only_on_tuesday]
  maineparnisari/document:2#writer@maineparnisari/user:1