// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: REDACTEDapi/api/acl_service.proto

package REDACTEDapi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RelationTupleFilter_Filter int32

const (
	RelationTupleFilter_UNKNOWN   RelationTupleFilter_Filter = 0
	RelationTupleFilter_OBJECT_ID RelationTupleFilter_Filter = 1
	RelationTupleFilter_RELATION  RelationTupleFilter_Filter = 2
	RelationTupleFilter_USER_ID   RelationTupleFilter_Filter = 3
	RelationTupleFilter_USERSET   RelationTupleFilter_Filter = 4
)

// Enum value maps for RelationTupleFilter_Filter.
var (
	RelationTupleFilter_Filter_name = map[int32]string{
		0: "UNKNOWN",
		1: "OBJECT_ID",
		2: "RELATION",
		3: "USER_ID",
		4: "USERSET",
	}
	RelationTupleFilter_Filter_value = map[string]int32{
		"UNKNOWN":   0,
		"OBJECT_ID": 1,
		"RELATION":  2,
		"USER_ID":   3,
		"USERSET":   4,
	}
)

func (x RelationTupleFilter_Filter) Enum() *RelationTupleFilter_Filter {
	p := new(RelationTupleFilter_Filter)
	*p = x
	return p
}

func (x RelationTupleFilter_Filter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationTupleFilter_Filter) Descriptor() protoreflect.EnumDescriptor {
	return file_REDACTEDapi_api_acl_service_proto_enumTypes[0].Descriptor()
}

func (RelationTupleFilter_Filter) Type() protoreflect.EnumType {
	return &file_REDACTEDapi_api_acl_service_proto_enumTypes[0]
}

func (x RelationTupleFilter_Filter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationTupleFilter_Filter.Descriptor instead.
func (RelationTupleFilter_Filter) EnumDescriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{0, 0}
}

type RelationTupleFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Setting any of these fields requires the appropriate filter type to be
	// added to the filters list as well
	ObjectId string                       `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation string                       `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	UserId   string                       `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Userset  *ObjectAndRelation           `protobuf:"bytes,5,opt,name=userset,proto3" json:"userset,omitempty"`
	Filters  []RelationTupleFilter_Filter `protobuf:"varint,6,rep,packed,name=filters,proto3,enum=RelationTupleFilter_Filter" json:"filters,omitempty"`
}

func (x *RelationTupleFilter) Reset() {
	*x = RelationTupleFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationTupleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTupleFilter) ProtoMessage() {}

func (x *RelationTupleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTupleFilter.ProtoReflect.Descriptor instead.
func (*RelationTupleFilter) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{0}
}

func (x *RelationTupleFilter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RelationTupleFilter) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RelationTupleFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationTupleFilter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RelationTupleFilter) GetUserset() *ObjectAndRelation {
	if x != nil {
		return x.Userset
	}
	return nil
}

func (x *RelationTupleFilter) GetFilters() []RelationTupleFilter_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A read request specifies one or multiple tuplesets and an optional zookie.
	Tuplesets  []*RelationTupleFilter `protobuf:"bytes,1,rep,name=tuplesets,proto3" json:"tuplesets,omitempty"`
	AtRevision *Zookie                `protobuf:"bytes,2,opt,name=at_revision,json=atRevision,proto3" json:"at_revision,omitempty"`
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReadRequest) GetTuplesets() []*RelationTupleFilter {
	if x != nil {
		return x.Tuplesets
	}
	return nil
}

func (x *ReadRequest) GetAtRevision() *Zookie {
	if x != nil {
		return x.AtRevision
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tuplesets []*ReadResponse_Tupleset `protobuf:"bytes,1,rep,name=tuplesets,proto3" json:"tuplesets,omitempty"`
	Revision  *Zookie                  `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadResponse) GetTuplesets() []*ReadResponse_Tupleset {
	if x != nil {
		return x.Tuplesets
	}
	return nil
}

func (x *ReadResponse) GetRevision() *Zookie {
	if x != nil {
		return x.Revision
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Clients may modify a single relation tuple to add or remove an ACL. They
	// may also modify all tuples related to an object via a read-modify-write
	// process with optimistic concurrency control [21] that uses a read RPC
	// followed by a write RPC:
	//
	// 1. Read all relation tuples of an object, including a per-object “lock”
	//    tuple.
	// 2. Generate the tuples to write or delete. Send the writes, along with a
	//    touch on the lock tuple, to Zanzibar, with the condition that the
	//    writes will be committed only if the lock tuple has not been modified
	//    since the read.
	// 3. If the write condition is not met, go back to step 1.
	//    The lock tuple is just a regular relation tuple used by clients to
	//    detect write races.
	//
	// The lock tuple is just a regular relation tuple used by clients to
	// detect write races.
	WriteConditions []*RelationTuple       `protobuf:"bytes,1,rep,name=write_conditions,json=writeConditions,proto3" json:"write_conditions,omitempty"` // To be bounded by configuration
	Updates         []*RelationTupleUpdate `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetWriteConditions() []*RelationTuple {
	if x != nil {
		return x.WriteConditions
	}
	return nil
}

func (x *WriteRequest) GetUpdates() []*RelationTupleUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revision *Zookie `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{4}
}

func (x *WriteResponse) GetRevision() *Zookie {
	if x != nil {
		return x.Revision
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A check request specifies a userset, represented by ⟨object#relation⟩,
	// a putative user, often represented by an authentication token, and a
	// zookie corresponding to the desired object version.
	TestUserset *ObjectAndRelation `protobuf:"bytes,1,opt,name=test_userset,json=testUserset,proto3" json:"test_userset,omitempty"`
	User        *User              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // TODO swap for putative user
	AtRevision  *Zookie            `protobuf:"bytes,3,opt,name=at_revision,json=atRevision,proto3" json:"at_revision,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckRequest) GetTestUserset() *ObjectAndRelation {
	if x != nil {
		return x.TestUserset
	}
	return nil
}

func (x *CheckRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CheckRequest) GetAtRevision() *Zookie {
	if x != nil {
		return x.AtRevision
	}
	return nil
}

type ContentChangeCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// To authorize application content modifications, our clients send a special
	// type of check request, a content-change check. A content-change check
	// request does not carry a zookie and is evaluated at the latest snapshot.
	TestUserset *ObjectAndRelation `protobuf:"bytes,1,opt,name=test_userset,json=testUserset,proto3" json:"test_userset,omitempty"`
	User        *User              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // TODO swap for a putative user
}

func (x *ContentChangeCheckRequest) Reset() {
	*x = ContentChangeCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentChangeCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentChangeCheckRequest) ProtoMessage() {}

func (x *ContentChangeCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentChangeCheckRequest.ProtoReflect.Descriptor instead.
func (*ContentChangeCheckRequest) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{6}
}

func (x *ContentChangeCheckRequest) GetTestUserset() *ObjectAndRelation {
	if x != nil {
		return x.TestUserset
	}
	return nil
}

func (x *ContentChangeCheckRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMember bool    `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Revision *Zookie `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{7}
}

func (x *CheckResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckResponse) GetRevision() *Zookie {
	if x != nil {
		return x.Revision
	}
	return nil
}

type ExpandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Expand API returns the effective userset given an ⟨object#relation⟩
	// pair and an optional zookie. Unlike the Read API, Expand follows indirect
	// references expressed through userset rewrite rules.
	Userset    *ObjectAndRelation `protobuf:"bytes,1,opt,name=userset,proto3" json:"userset,omitempty"`
	AtRevision *Zookie            `protobuf:"bytes,2,opt,name=at_revision,json=atRevision,proto3" json:"at_revision,omitempty"`
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{8}
}

func (x *ExpandRequest) GetUserset() *ObjectAndRelation {
	if x != nil {
		return x.Userset
	}
	return nil
}

func (x *ExpandRequest) GetAtRevision() *Zookie {
	if x != nil {
		return x.AtRevision
	}
	return nil
}

type ExpandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The result is represented by a userset tree whose leaf nodes are user IDs
	// or usersets pointing to other ⟨object#relation⟩ pairs, and intermediate
	// nodes represent union, intersection, or exclusion operators.
	TreeNode *RelationTupleTreeNode `protobuf:"bytes,1,opt,name=tree_node,json=treeNode,proto3" json:"tree_node,omitempty"`
	Revision *Zookie                `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{9}
}

func (x *ExpandResponse) GetTreeNode() *RelationTupleTreeNode {
	if x != nil {
		return x.TreeNode
	}
	return nil
}

func (x *ExpandResponse) GetRevision() *Zookie {
	if x != nil {
		return x.Revision
	}
	return nil
}

type ReadResponse_Tupleset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tuples []*RelationTuple `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
}

func (x *ReadResponse_Tupleset) Reset() {
	*x = ReadResponse_Tupleset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse_Tupleset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse_Tupleset) ProtoMessage() {}

func (x *ReadResponse_Tupleset) ProtoReflect() protoreflect.Message {
	mi := &file_REDACTEDapi_api_acl_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse_Tupleset.ProtoReflect.Descriptor instead.
func (*ReadResponse_Tupleset) Descriptor() ([]byte, []int) {
	return file_REDACTEDapi_api_acl_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReadResponse_Tupleset) GetTuples() []*RelationTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

var File_REDACTEDapi_api_acl_service_proto protoreflect.FileDescriptor

var file_REDACTEDapi_api_acl_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x63, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x02,
	0x0a, 0x13, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41,
	0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x75, 0x70, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x4c, 0x0a, 0x06, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x49, 0x44, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x49, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x53, 0x45, 0x52, 0x53, 0x45, 0x54, 0x10, 0x04, 0x22, 0x6b, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x74, 0x75, 0x70, 0x6c, 0x65,
	0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x09, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x0b, 0x61,
	0x74, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x5a, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x52, 0x65, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x9d, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73,
	0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x65,
	0x74, 0x52, 0x09, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x08,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x5a, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0x32, 0x0a, 0x08, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x12, 0x26, 0x0a,
	0x06, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x74,
	0x75, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x79, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x10, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52,
	0x0f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x2e, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x34, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x5a, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x65, 0x74, 0x12, 0x19,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0b, 0x61, 0x74, 0x5f,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x5a, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x35, 0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41,
	0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x65, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x51, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x23, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x5a, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x08, 0x72, 0x65, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x67, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x41, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x0b, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x5a, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6a,
	0x0a, 0x0e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x09, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x54, 0x72, 0x65, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x74, 0x72, 0x65,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x5a, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0xf8, 0x01, 0x0a, 0x0a, 0x41,
	0x43, 0x4c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x52, 0x65, 0x61,
	0x64, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x28, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x05, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x0d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1a, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x61,
	0x6e, 0x64, 0x12, 0x0e, 0x2e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x63, 0x6f,
	0x64, 0x65, 0x2f, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_REDACTEDapi_api_acl_service_proto_rawDescOnce sync.Once
	file_REDACTEDapi_api_acl_service_proto_rawDescData = file_REDACTEDapi_api_acl_service_proto_rawDesc
)

func file_REDACTEDapi_api_acl_service_proto_rawDescGZIP() []byte {
	file_REDACTEDapi_api_acl_service_proto_rawDescOnce.Do(func() {
		file_REDACTEDapi_api_acl_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_REDACTEDapi_api_acl_service_proto_rawDescData)
	})
	return file_REDACTEDapi_api_acl_service_proto_rawDescData
}

var file_REDACTEDapi_api_acl_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_REDACTEDapi_api_acl_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_REDACTEDapi_api_acl_service_proto_goTypes = []interface{}{
	(RelationTupleFilter_Filter)(0),   // 0: RelationTupleFilter.Filter
	(*RelationTupleFilter)(nil),       // 1: RelationTupleFilter
	(*ReadRequest)(nil),               // 2: ReadRequest
	(*ReadResponse)(nil),              // 3: ReadResponse
	(*WriteRequest)(nil),              // 4: WriteRequest
	(*WriteResponse)(nil),             // 5: WriteResponse
	(*CheckRequest)(nil),              // 6: CheckRequest
	(*ContentChangeCheckRequest)(nil), // 7: ContentChangeCheckRequest
	(*CheckResponse)(nil),             // 8: CheckResponse
	(*ExpandRequest)(nil),             // 9: ExpandRequest
	(*ExpandResponse)(nil),            // 10: ExpandResponse
	(*ReadResponse_Tupleset)(nil),     // 11: ReadResponse.Tupleset
	(*ObjectAndRelation)(nil),         // 12: ObjectAndRelation
	(*Zookie)(nil),                    // 13: Zookie
	(*RelationTuple)(nil),             // 14: RelationTuple
	(*RelationTupleUpdate)(nil),       // 15: RelationTupleUpdate
	(*User)(nil),                      // 16: User
	(*RelationTupleTreeNode)(nil),     // 17: RelationTupleTreeNode
}
var file_REDACTEDapi_api_acl_service_proto_depIdxs = []int32{
	12, // 0: RelationTupleFilter.userset:type_name -> ObjectAndRelation
	0,  // 1: RelationTupleFilter.filters:type_name -> RelationTupleFilter.Filter
	1,  // 2: ReadRequest.tuplesets:type_name -> RelationTupleFilter
	13, // 3: ReadRequest.at_revision:type_name -> Zookie
	11, // 4: ReadResponse.tuplesets:type_name -> ReadResponse.Tupleset
	13, // 5: ReadResponse.revision:type_name -> Zookie
	14, // 6: WriteRequest.write_conditions:type_name -> RelationTuple
	15, // 7: WriteRequest.updates:type_name -> RelationTupleUpdate
	13, // 8: WriteResponse.revision:type_name -> Zookie
	12, // 9: CheckRequest.test_userset:type_name -> ObjectAndRelation
	16, // 10: CheckRequest.user:type_name -> User
	13, // 11: CheckRequest.at_revision:type_name -> Zookie
	12, // 12: ContentChangeCheckRequest.test_userset:type_name -> ObjectAndRelation
	16, // 13: ContentChangeCheckRequest.user:type_name -> User
	13, // 14: CheckResponse.revision:type_name -> Zookie
	12, // 15: ExpandRequest.userset:type_name -> ObjectAndRelation
	13, // 16: ExpandRequest.at_revision:type_name -> Zookie
	17, // 17: ExpandResponse.tree_node:type_name -> RelationTupleTreeNode
	13, // 18: ExpandResponse.revision:type_name -> Zookie
	14, // 19: ReadResponse.Tupleset.tuples:type_name -> RelationTuple
	2,  // 20: ACLService.Read:input_type -> ReadRequest
	4,  // 21: ACLService.Write:input_type -> WriteRequest
	6,  // 22: ACLService.Check:input_type -> CheckRequest
	7,  // 23: ACLService.ContentChangeCheck:input_type -> ContentChangeCheckRequest
	9,  // 24: ACLService.Expand:input_type -> ExpandRequest
	3,  // 25: ACLService.Read:output_type -> ReadResponse
	5,  // 26: ACLService.Write:output_type -> WriteResponse
	8,  // 27: ACLService.Check:output_type -> CheckResponse
	8,  // 28: ACLService.ContentChangeCheck:output_type -> CheckResponse
	10, // 29: ACLService.Expand:output_type -> ExpandResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_REDACTEDapi_api_acl_service_proto_init() }
func file_REDACTEDapi_api_acl_service_proto_init() {
	if File_REDACTEDapi_api_acl_service_proto != nil {
		return
	}
	file_REDACTEDapi_api_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_REDACTEDapi_api_acl_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationTupleFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentChangeCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_REDACTEDapi_api_acl_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse_Tupleset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_REDACTEDapi_api_acl_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_REDACTEDapi_api_acl_service_proto_goTypes,
		DependencyIndexes: file_REDACTEDapi_api_acl_service_proto_depIdxs,
		EnumInfos:         file_REDACTEDapi_api_acl_service_proto_enumTypes,
		MessageInfos:      file_REDACTEDapi_api_acl_service_proto_msgTypes,
	}.Build()
	File_REDACTEDapi_api_acl_service_proto = out.File
	file_REDACTEDapi_api_acl_service_proto_rawDesc = nil
	file_REDACTEDapi_api_acl_service_proto_goTypes = nil
	file_REDACTEDapi_api_acl_service_proto_depIdxs = nil
}
