---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/magefiles"
      - "/e2e"
      - "/tools/analyzers"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependencies"
    groups:
      go-mod:
        patterns: ["*"]
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependencies"
    groups:
      docker:
        patterns: ["*"]
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns: ["*"]
    cooldown:
      default-days: 7
