---
version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "depguard"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gocritic"
    - "goprintffuncname"
    - "gosec"
    - "govet"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "spancheck"
    - "staticcheck"
    - "tagalign"
    - "testifylint"
    - "tparallel"
    - "unconvert"
    - "usetesting"
    - "wastedassign"
    - "whitespace"
    - "unused"
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "k8s.io/utils/strings/slices$"
              desc: "use github.com/samber/lo"
    staticcheck:
      checks:
        - "all"
    revive:
      rules:
        - name: "unused-parameter"
          disabled: true
    rowserrcheck:
      packages:
        - "github.com/jmoiron/sqlx"
        - "github.com/jackc/pgx"
  exclusions:
    generated: "lax"
    presets:
      - "comments"
      - "common-false-positives"
      - "legacy"
      - "std-error-handling"
    rules:
      - linters:
          - "errcheck"
        text: "tx.Rollback()"
      - linters:
          - "staticcheck"
        path: "internal/services/"
        text: "SA1019"
      - linters:
          - "staticcheck"
        path: "internal/middleware/consistency/"
        text: "SA1019"
      - linters:
          - "staticcheck"
        path: "pkg/proto/core/v1/core.pb.validate.manual.go"
        text: "ST1003"
      - linters:
          - "revive"
        path: "pkg/proto/core/v1/core.pb.validate.manual.go"
        text: "var-naming"
      - linters:
          - "revive"
        text: 'receiver-naming: receiver name \S+ should be consistent with previous receiver name \S+ for invalid-type'
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
formatters:
  enable:
    - "gci"
    - "gofumpt"
    - "goimports"
  settings:
    gci:
      sections:
        - "standard"
        - "default"
        - "prefix(github.com/authzed)"
        - "localmodule"
    goimports:
      local-prefixes:
        - "github.com/authzed/spicedb"
  exclusions:
    generated: "lax"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
