---
run:
  timeout: "5m"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/spicedb"
  rowserrcheck:
    packages:
      - "github.com/jmoiron/sqlx"
      - "github.com/jackc/pgx"
  gosec:
    excludes:
      - "G404"  # Allow the usage of math/rand
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "deadcode"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "ifshort"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "stylecheck"
    - "tenv"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "varcheck"
    - "wastedassign"
    - "whitespace"
issues:
  exclude-rules:
    - text: "tx.Rollback()"
      linters:
        - "errcheck"
    # NOTE: temporarily disable deprecation checks for v0.
    - path: "internal/services/"
      linters:
        - "staticcheck"
      text: "SA1019"
    - path: "internal/middleware/consistency/"
      linters:
        - "staticcheck"
      text: "SA1019"
    - path: "pkg/proto/core/v1/core.pb.validate.manual.go"  # Ignore manual definition of metadata map
      linters:
        - "stylecheck"
      text: "ST1003"
    - path: "pkg/proto/core/v1/core.pb.validate.manual.go"  # Ignore manual definition of metadata map
      linters:
        - "revive"
      text: "var-naming"
