---
run:
  timeout: '5m'
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: 'github.com/authzed/spicedb'
  rowserrcheck:
    packages:
      - 'github.com/jmoiron/sqlx'
      - 'github.com/jackc/pgx'
  revive:
    rules:
      - name: 'unused-parameter'
        disabled: true
linters:
  enable:
    - 'bidichk'
    - 'bodyclose'
    - 'errcheck'
    - 'errname'
    - 'errorlint'
    - 'gofumpt'
    - 'goimports'
    - 'goprintffuncname'
    - 'gosec'
    - 'gosimple'
    - 'govet'
    - 'importas'
    - 'ineffassign'
    - 'makezero'
    - 'prealloc'
    - 'predeclared'
    - 'promlinter'
    - 'revive'
    - 'rowserrcheck'
    - 'staticcheck'
    - 'stylecheck'
    - 'tenv'
    - 'typecheck'
    - 'unconvert'
    - 'unused'
    - 'wastedassign'
    - 'whitespace'
issues:
  exclude-rules:
    - text: 'tx.Rollback()'
      linters:
        - 'errcheck'
    # NOTE: temporarily disable deprecation checks for v0.
    - path: 'internal/services/'
      linters:
        - 'staticcheck'
      text: 'SA1019'
    - path: 'internal/middleware/consistency/'
      linters:
        - 'staticcheck'
      text: 'SA1019'
    - path: 'pkg/proto/core/v1/core.pb.validate.manual.go'  # Ignore manual definition of metadata map
      linters:
        - 'stylecheck'
      text: 'ST1003'
    - path: 'pkg/proto/core/v1/core.pb.validate.manual.go'  # Ignore manual definition of metadata map
      linters:
        - 'revive'
      text: 'var-naming'
    # Ignore receiver errors for generic types not understood by the linter.
    - linters:
        - 'revive'
      text: 'receiver-naming: receiver name \S+ should be consistent with previous receiver name \S+ for invalid-type'
