# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
---
version: 2
builds:
  - main: "./cmd/spicedb"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
    goarch:
      - "amd64"
      - "arm64"
      - "riscv64"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - "-s -w"
      - "-X github.com/jzelinskie/cobrautil/v2.Version=v{{ .Version }}"
kos:
  - id: "spicedb"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    tags:
      - "latest"
      - "v{{ .Version }}"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"

  - id: "debug"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    base_image: "cgr.dev/chainguard/busybox"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    tags:
      - "latest-debug"
      - "v{{ .Version }}-debug"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"

  # ARM64
  - id: "arm64"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    platforms:
      - "linux/arm64"
    tags:
      - "v{{ .Version }}-arm64"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"
  - id: "arm64-debug"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    base_image: "cgr.dev/chainguard/busybox"
    platforms:
      - "linux/arm64"
    tags:
      - "v{{ .Version }}-arm64-debug"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"

  # AMD64
  - id: "amd64"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    platforms:
      - "linux/amd64"
    tags:
      - "v{{ .Version }}-amd64"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"
  - id: "amd64-debug"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    base_image: "cgr.dev/chainguard/busybox"
    platforms:
      - "linux/amd64"
    tags:
      - "v{{ .Version }}-amd64-debug"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"

  # RISCV64
  - id: "riscv64"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    platforms:
      - "linux/riscv64"
    tags:
      - "v{{ .Version }}-riscv64"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"
  - id: "riscv64-debug"
    build: "spicedb"
    repositories:
      - "quay.io/authzed/spicedb-git"
      - "ghcr.io/authzed/spicedb-git"
      - "authzed/spicedb-git"
    base_image: "riscv64/busybox"
    platforms:
      - "linux/riscv64"
    tags:
      - "v{{ .Version }}-riscv64-debug"
    creation_time: "{{ .CommitTimestamp }}"
    ko_data_creation_time: "{{ .CommitTimestamp }}"
    bare: true
    sbom: "none"

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
nightly:
  version_template: "{{ incpatch .Version }}-{{ .ShortCommit }}"
