---
builds:
  - main: "./cmd/spicedb"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
#      - "windows"
#      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - "-s -w"
      - "-X github.com/jzelinskie/cobrautil/v2.Version=v{{ .Version }}"

dockers:
  # AMD64
  - image_templates:
      - &amd_image_gh "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:v{{ .Version }}-amd64"
    dockerfile: &dockerfile "Dockerfile.release"
    goos: "linux"
    goarch: "amd64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
  # AMD64 (debug)
  - image_templates:
      - &amd_debug_image_gh "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:v{{ .Version }}-amd64-debug"
    dockerfile: &dockerfile "Dockerfile.release"
    goos: "linux"
    goarch: "amd64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=BASE=cgr.dev/chainguard/busybox"
  # ARM64
  - image_templates:
      - &arm_image_gh "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:v{{ .Version }}-arm64"
    dockerfile: *dockerfile
    goos: "linux"
    goarch: "arm64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/arm64"
  # ARM64 (debug)
  - image_templates:
      - &arm_debug_image_gh "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:v{{ .Version }}-arm64-debug"
    dockerfile: *dockerfile
    goos: "linux"
    goarch: "arm64"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=BASE=cgr.dev/chainguard/busybox"
docker_manifests:
  - name_template: "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:v{{ .Version }}"
    image_templates: [*amd_image_gh, *arm_image_gh]
  - name_template: "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:latest"
    image_templates: [*amd_image_gh, *arm_image_gh]

  # Debug Images:

  # GitHub Registry
  - name_template: "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:v{{ .Version }}-debug"
    image_templates: [*amd_debug_image_gh, *arm_debug_image_gh]
  - name_template: "ghcr.io/vtl3000/spicedb{{ if .IsNightly }}-git{{ end }}:latest-debug"
    image_templates: [*amd_debug_image_gh, *arm_debug_image_gh]

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: "github-native"
  sort: "asc"
#nightly:
#  name_template: "{{ incpatch .Version }}-{{ .ShortCommit }}"
release:
  draft: true
  prerelease: "auto"
  mode: "replace"
  footer: |
    ## Docker Images
    This release is available at `ghcr.io/vtl3000/spicedb:v{{ .Version }}`
