// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package datastore

import (
	defaults "github.com/creasty/defaults"
	"time"
)

type ConnPoolConfigOption func(c *ConnPoolConfig)

// NewConnPoolConfigWithOptions creates a new ConnPoolConfig with the passed in options set
func NewConnPoolConfigWithOptions(opts ...ConnPoolConfigOption) *ConnPoolConfig {
	c := &ConnPoolConfig{}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// NewConnPoolConfigWithOptionsAndDefaults creates a new ConnPoolConfig with the passed in options set starting from the defaults
func NewConnPoolConfigWithOptionsAndDefaults(opts ...ConnPoolConfigOption) *ConnPoolConfig {
	c := &ConnPoolConfig{}
	defaults.MustSet(c)
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// ToOption returns a new ConnPoolConfigOption that sets the values from the passed in ConnPoolConfig
func (c *ConnPoolConfig) ToOption() ConnPoolConfigOption {
	return func(to *ConnPoolConfig) {
		to.MaxIdleTime = c.MaxIdleTime
		to.MaxLifetime = c.MaxLifetime
		to.MaxLifetimeJitter = c.MaxLifetimeJitter
		to.MaxOpenConns = c.MaxOpenConns
		to.MinOpenConns = c.MinOpenConns
		to.HealthCheckInterval = c.HealthCheckInterval
	}
}

// DebugMap returns a map form of ConnPoolConfig for debugging
func (c *ConnPoolConfig) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if dm, ok := any(&c.MaxIdleTime).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["MaxIdleTime"] = dm.DebugMap()
	} else {
		debugMap["MaxIdleTime"] = c.MaxIdleTime
	}
	if dm, ok := any(&c.MaxLifetime).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["MaxLifetime"] = dm.DebugMap()
	} else {
		debugMap["MaxLifetime"] = c.MaxLifetime
	}
	if dm, ok := any(&c.MaxLifetimeJitter).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["MaxLifetimeJitter"] = dm.DebugMap()
	} else {
		debugMap["MaxLifetimeJitter"] = c.MaxLifetimeJitter
	}
	debugMap["MaxOpenConns"] = c.MaxOpenConns
	debugMap["MinOpenConns"] = c.MinOpenConns
	if dm, ok := any(&c.HealthCheckInterval).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["HealthCheckInterval"] = dm.DebugMap()
	} else {
		debugMap["HealthCheckInterval"] = c.HealthCheckInterval
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of ConnPoolConfig for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (c *ConnPoolConfig) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(c.DebugMap())
}

// ConnPoolConfigWithOptions configures an existing ConnPoolConfig with the passed in options set
func ConnPoolConfigWithOptions(c *ConnPoolConfig, opts ...ConnPoolConfigOption) *ConnPoolConfig {
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// WithOptions configures the receiver ConnPoolConfig with the passed in options set
func (c *ConnPoolConfig) WithOptions(opts ...ConnPoolConfigOption) *ConnPoolConfig {
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// WithMaxIdleTime returns an option that can set MaxIdleTime on a ConnPoolConfig
func WithMaxIdleTime(maxIdleTime time.Duration) ConnPoolConfigOption {
	return func(c *ConnPoolConfig) {
		c.MaxIdleTime = maxIdleTime
	}
}

// WithMaxLifetime returns an option that can set MaxLifetime on a ConnPoolConfig
func WithMaxLifetime(maxLifetime time.Duration) ConnPoolConfigOption {
	return func(c *ConnPoolConfig) {
		c.MaxLifetime = maxLifetime
	}
}

// WithMaxLifetimeJitter returns an option that can set MaxLifetimeJitter on a ConnPoolConfig
func WithMaxLifetimeJitter(maxLifetimeJitter time.Duration) ConnPoolConfigOption {
	return func(c *ConnPoolConfig) {
		c.MaxLifetimeJitter = maxLifetimeJitter
	}
}

// WithMaxOpenConns returns an option that can set MaxOpenConns on a ConnPoolConfig
func WithMaxOpenConns(maxOpenConns int) ConnPoolConfigOption {
	return func(c *ConnPoolConfig) {
		c.MaxOpenConns = maxOpenConns
	}
}

// WithMinOpenConns returns an option that can set MinOpenConns on a ConnPoolConfig
func WithMinOpenConns(minOpenConns int) ConnPoolConfigOption {
	return func(c *ConnPoolConfig) {
		c.MinOpenConns = minOpenConns
	}
}

// WithHealthCheckInterval returns an option that can set HealthCheckInterval on a ConnPoolConfig
func WithHealthCheckInterval(healthCheckInterval time.Duration) ConnPoolConfigOption {
	return func(c *ConnPoolConfig) {
		c.HealthCheckInterval = healthCheckInterval
	}
}
