// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package datastore

import defaults "github.com/creasty/defaults"

type RelIntegrityKeyOption func(r *RelIntegrityKey)

// NewRelIntegrityKeyWithOptions creates a new RelIntegrityKey with the passed in options set
func NewRelIntegrityKeyWithOptions(opts ...RelIntegrityKeyOption) *RelIntegrityKey {
	r := &RelIntegrityKey{}
	for _, o := range opts {
		o(r)
	}
	return r
}

// NewRelIntegrityKeyWithOptionsAndDefaults creates a new RelIntegrityKey with the passed in options set starting from the defaults
func NewRelIntegrityKeyWithOptionsAndDefaults(opts ...RelIntegrityKeyOption) *RelIntegrityKey {
	r := &RelIntegrityKey{}
	defaults.MustSet(r)
	for _, o := range opts {
		o(r)
	}
	return r
}

// ToOption returns a new RelIntegrityKeyOption that sets the values from the passed in RelIntegrityKey
func (r *RelIntegrityKey) ToOption() RelIntegrityKeyOption {
	return func(to *RelIntegrityKey) {
		to.KeyID = r.KeyID
		to.KeyFilename = r.KeyFilename
	}
}

// DebugMap returns a map form of RelIntegrityKey for debugging
func (r *RelIntegrityKey) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if r.KeyID == "" {
		debugMap["KeyID"] = "(empty)"
	} else {
		debugMap["KeyID"] = r.KeyID
	}
	if r.KeyFilename == "" {
		debugMap["KeyFilename"] = "(empty)"
	} else {
		debugMap["KeyFilename"] = r.KeyFilename
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of RelIntegrityKey for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (r *RelIntegrityKey) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(r.DebugMap())
}

// RelIntegrityKeyWithOptions configures an existing RelIntegrityKey with the passed in options set
func RelIntegrityKeyWithOptions(r *RelIntegrityKey, opts ...RelIntegrityKeyOption) *RelIntegrityKey {
	for _, o := range opts {
		o(r)
	}
	return r
}

// WithOptions configures the receiver RelIntegrityKey with the passed in options set
func (r *RelIntegrityKey) WithOptions(opts ...RelIntegrityKeyOption) *RelIntegrityKey {
	for _, o := range opts {
		o(r)
	}
	return r
}

// WithKeyID returns an option that can set KeyID on a RelIntegrityKey
func WithKeyID(keyID string) RelIntegrityKeyOption {
	return func(r *RelIntegrityKey) {
		r.KeyID = keyID
	}
}

// WithKeyFilename returns an option that can set KeyFilename on a RelIntegrityKey
func WithKeyFilename(keyFilename string) RelIntegrityKeyOption {
	return func(r *RelIntegrityKey) {
		r.KeyFilename = keyFilename
	}
}
