---
name: "🐞 Bug Report"
description: "Tell us about something that's not working the way we (probably) intend."
labels: ["kind/bug", "state/triage"]
body:
  - type: "textarea"
    id: "version"
    validations:
      required: true
    attributes:
      label: "What SpiceDB version are you using?"
      placeholder: "v1.25.0"
  - type: "textarea"
    id: "config"
    validations:
      required: false
    attributes:
      label: "What SpiceDB flags do you use?"
      placeholder: |-
        1. --datastore-engine=...
        2. --enable-experimental-watchable-schema-cache=...

        SpiceDB emits a log line with `message: configuration` printing them all out.
  - type: "textarea"
    id: "config"
    validations:
      required: false
    attributes:
      label: "Any other details?"
      placeholder: |-
        - `zed schema read` will print the schema. This is helpful to debug some correctness and performance issues.
        - What traffic was SpiceDB getting at the time of the event? (e.g. 100 RPS for `CheckPermissions` via the zed client)
        - What environment are you running in? (e.g. Kubernetes, ECS, etc.)
  - type: "textarea"
    id: "repro"
    validations:
      required: true
    attributes:
      label: "Steps to Reproduce"
      description: "How can we see what you're seeing? Specific is terrific."
      placeholder: |-
        1. foo
        2. bar
        3. baz
  - type: "textarea"
    id: "expected"
    validations:
      required: true
    attributes:
      label: "Expected Result"
  - type: "textarea"
    id: "actual"
    validations:
      required: true
    attributes:
      label: "Actual Result"
      description: "Logs? Screenshots? Yes, please."