apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: time-shift
spec:
  mode: one
  clockIds: ["CLOCK_REALTIME", "CLOCK_MONOTONIC"]
  selector:
    labelSelectors:
      statefulset.kubernetes.io/pod-name: crdb-1
  timeOffset: '-200ms'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      statefulset.kubernetes.io/pod-name: crdb-0
  delay:
    latency: '100ms'
    jitter: '10ms'
