// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: REDACTEDapi/api/metadata.proto

package REDACTEDapi

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on DocComment with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *DocComment) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Comment

	return nil
}

// DocCommentValidationError is the validation error returned by
// DocComment.Validate if the designated constraints aren't met.
type DocCommentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocCommentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocCommentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocCommentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocCommentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocCommentValidationError) ErrorName() string { return "DocCommentValidationError" }

// Error satisfies the builtin error interface
func (e DocCommentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocComment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocCommentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocCommentValidationError{}

// Validate checks the field values on RelationMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *RelationMetadata) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Kind

	return nil
}

// RelationMetadataValidationError is the validation error returned by
// RelationMetadata.Validate if the designated constraints aren't met.
type RelationMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RelationMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RelationMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RelationMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RelationMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RelationMetadataValidationError) ErrorName() string { return "RelationMetadataValidationError" }

// Error satisfies the builtin error interface
func (e RelationMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRelationMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RelationMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RelationMetadataValidationError{}
