// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package options

import (
	queryshape "github.com/authzed/spicedb/pkg/datastore/queryshape"
	defaults "github.com/creasty/defaults"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

type QueryOptionsOption func(q *QueryOptions)

// NewQueryOptionsWithOptions creates a new QueryOptions with the passed in options set
func NewQueryOptionsWithOptions(opts ...QueryOptionsOption) *QueryOptions {
	q := &QueryOptions{}
	for _, opt := range opts {
		opt(q)
	}
	return q
}

// NewQueryOptionsWithOptionsAndDefaults creates a new QueryOptions with the passed in options set starting from the defaults
func NewQueryOptionsWithOptionsAndDefaults(opts ...QueryOptionsOption) *QueryOptions {
	q := &QueryOptions{}
	defaults.MustSet(q)
	for _, opt := range opts {
		opt(q)
	}
	return q
}

// ToOption returns a new QueryOptionsOption that sets the values from the passed in QueryOptions
func (q *QueryOptions) ToOption() QueryOptionsOption {
	return func(to *QueryOptions) {
		to.Limit = q.Limit
		to.Sort = q.Sort
		to.After = q.After
		to.BeforeOrEqual = q.BeforeOrEqual
		to.SkipCaveats = q.SkipCaveats
		to.SkipExpiration = q.SkipExpiration
		to.SQLCheckAssertionForTest = q.SQLCheckAssertionForTest
		to.SQLExplainCallbackForTest = q.SQLExplainCallbackForTest
		to.QueryShape = q.QueryShape
	}
}

// DebugMap returns a map form of QueryOptions for debugging
func (q *QueryOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if q.Limit == nil {
		debugMap["Limit"] = "nil"
	} else if dm, ok := any(q.Limit).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Limit"] = dm.DebugMap()
	} else {
		debugMap["Limit"] = *q.Limit
	}
	if dm, ok := any(&q.Sort).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Sort"] = dm.DebugMap()
	} else {
		debugMap["Sort"] = q.Sort
	}
	if dm, ok := any(&q.After).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["After"] = dm.DebugMap()
	} else {
		debugMap["After"] = q.After
	}
	if dm, ok := any(&q.BeforeOrEqual).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["BeforeOrEqual"] = dm.DebugMap()
	} else {
		debugMap["BeforeOrEqual"] = q.BeforeOrEqual
	}
	debugMap["SkipCaveats"] = q.SkipCaveats
	debugMap["SkipExpiration"] = q.SkipExpiration
	if dm, ok := any(&q.SQLCheckAssertionForTest).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["SQLCheckAssertionForTest"] = dm.DebugMap()
	} else {
		debugMap["SQLCheckAssertionForTest"] = q.SQLCheckAssertionForTest
	}
	if dm, ok := any(&q.SQLExplainCallbackForTest).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["SQLExplainCallbackForTest"] = dm.DebugMap()
	} else {
		debugMap["SQLExplainCallbackForTest"] = q.SQLExplainCallbackForTest
	}
	if dm, ok := any(&q.QueryShape).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["QueryShape"] = dm.DebugMap()
	} else {
		debugMap["QueryShape"] = q.QueryShape
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of QueryOptions for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (q *QueryOptions) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(q.DebugMap())
}

// QueryOptionsWithOptions configures an existing QueryOptions with the passed in options set
func QueryOptionsWithOptions(q *QueryOptions, opts ...QueryOptionsOption) *QueryOptions {
	for _, opt := range opts {
		opt(q)
	}
	return q
}

// WithOptions configures the receiver QueryOptions with the passed in options set
func (q *QueryOptions) WithOptions(opts ...QueryOptionsOption) *QueryOptions {
	for _, opt := range opts {
		opt(q)
	}
	return q
}

// WithLimit returns an option that can set Limit on a QueryOptions
func WithLimit(limit *uint64) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.Limit = limit
	}
}

// WithSort returns an option that can set Sort on a QueryOptions
func WithSort(sort SortOrder) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.Sort = sort
	}
}

// WithAfter returns an option that can set After on a QueryOptions
func WithAfter(after Cursor) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.After = after
	}
}

// WithBeforeOrEqual returns an option that can set BeforeOrEqual on a QueryOptions
func WithBeforeOrEqual(beforeOrEqual Cursor) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.BeforeOrEqual = beforeOrEqual
	}
}

// WithSkipCaveats returns an option that can set SkipCaveats on a QueryOptions
func WithSkipCaveats(skipCaveats bool) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.SkipCaveats = skipCaveats
	}
}

// WithSkipExpiration returns an option that can set SkipExpiration on a QueryOptions
func WithSkipExpiration(skipExpiration bool) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.SkipExpiration = skipExpiration
	}
}

// WithSQLCheckAssertionForTest returns an option that can set SQLCheckAssertionForTest on a QueryOptions
func WithSQLCheckAssertionForTest(sQLCheckAssertionForTest SQLCheckAssertionForTest) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.SQLCheckAssertionForTest = sQLCheckAssertionForTest
	}
}

// WithSQLExplainCallbackForTest returns an option that can set SQLExplainCallbackForTest on a QueryOptions
func WithSQLExplainCallbackForTest(sQLExplainCallbackForTest SQLExplainCallbackForTest) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.SQLExplainCallbackForTest = sQLExplainCallbackForTest
	}
}

// WithQueryShape returns an option that can set QueryShape on a QueryOptions
func WithQueryShape(queryShape queryshape.Shape) QueryOptionsOption {
	return func(q *QueryOptions) {
		q.QueryShape = queryShape
	}
}

type ReverseQueryOptionsOption func(r *ReverseQueryOptions)

// NewReverseQueryOptionsWithOptions creates a new ReverseQueryOptions with the passed in options set
func NewReverseQueryOptionsWithOptions(opts ...ReverseQueryOptionsOption) *ReverseQueryOptions {
	r := &ReverseQueryOptions{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// NewReverseQueryOptionsWithOptionsAndDefaults creates a new ReverseQueryOptions with the passed in options set starting from the defaults
func NewReverseQueryOptionsWithOptionsAndDefaults(opts ...ReverseQueryOptionsOption) *ReverseQueryOptions {
	r := &ReverseQueryOptions{}
	defaults.MustSet(r)
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// ToOption returns a new ReverseQueryOptionsOption that sets the values from the passed in ReverseQueryOptions
func (r *ReverseQueryOptions) ToOption() ReverseQueryOptionsOption {
	return func(to *ReverseQueryOptions) {
		to.ResRelation = r.ResRelation
		to.LimitForReverse = r.LimitForReverse
		to.SortForReverse = r.SortForReverse
		to.AfterForReverse = r.AfterForReverse
		to.SkipCaveatsForReverse = r.SkipCaveatsForReverse
		to.SkipExpirationForReverse = r.SkipExpirationForReverse
		to.SQLExplainCallbackForTestForReverse = r.SQLExplainCallbackForTestForReverse
		to.QueryShapeForReverse = r.QueryShapeForReverse
	}
}

// DebugMap returns a map form of ReverseQueryOptions for debugging
func (r *ReverseQueryOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	if r.ResRelation == nil {
		debugMap["ResRelation"] = "nil"
	} else if dm, ok := any(r.ResRelation).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["ResRelation"] = dm.DebugMap()
	} else {
		debugMap["ResRelation"] = *r.ResRelation
	}
	if r.LimitForReverse == nil {
		debugMap["LimitForReverse"] = "nil"
	} else if dm, ok := any(r.LimitForReverse).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["LimitForReverse"] = dm.DebugMap()
	} else {
		debugMap["LimitForReverse"] = *r.LimitForReverse
	}
	if dm, ok := any(&r.SortForReverse).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["SortForReverse"] = dm.DebugMap()
	} else {
		debugMap["SortForReverse"] = r.SortForReverse
	}
	if dm, ok := any(&r.AfterForReverse).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["AfterForReverse"] = dm.DebugMap()
	} else {
		debugMap["AfterForReverse"] = r.AfterForReverse
	}
	debugMap["SkipCaveatsForReverse"] = r.SkipCaveatsForReverse
	debugMap["SkipExpirationForReverse"] = r.SkipExpirationForReverse
	if dm, ok := any(&r.SQLExplainCallbackForTestForReverse).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["SQLExplainCallbackForTestForReverse"] = dm.DebugMap()
	} else {
		debugMap["SQLExplainCallbackForTestForReverse"] = r.SQLExplainCallbackForTestForReverse
	}
	if dm, ok := any(&r.QueryShapeForReverse).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["QueryShapeForReverse"] = dm.DebugMap()
	} else {
		debugMap["QueryShapeForReverse"] = r.QueryShapeForReverse
	}
	return debugMap
}

// FlatDebugMap returns a flattened map form of ReverseQueryOptions for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (r *ReverseQueryOptions) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(r.DebugMap())
}

// ReverseQueryOptionsWithOptions configures an existing ReverseQueryOptions with the passed in options set
func ReverseQueryOptionsWithOptions(r *ReverseQueryOptions, opts ...ReverseQueryOptionsOption) *ReverseQueryOptions {
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithOptions configures the receiver ReverseQueryOptions with the passed in options set
func (r *ReverseQueryOptions) WithOptions(opts ...ReverseQueryOptionsOption) *ReverseQueryOptions {
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithResRelation returns an option that can set ResRelation on a ReverseQueryOptions
func WithResRelation(resRelation *ResourceRelation) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.ResRelation = resRelation
	}
}

// WithLimitForReverse returns an option that can set LimitForReverse on a ReverseQueryOptions
func WithLimitForReverse(limitForReverse *uint64) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.LimitForReverse = limitForReverse
	}
}

// WithSortForReverse returns an option that can set SortForReverse on a ReverseQueryOptions
func WithSortForReverse(sortForReverse SortOrder) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.SortForReverse = sortForReverse
	}
}

// WithAfterForReverse returns an option that can set AfterForReverse on a ReverseQueryOptions
func WithAfterForReverse(afterForReverse Cursor) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.AfterForReverse = afterForReverse
	}
}

// WithSkipCaveatsForReverse returns an option that can set SkipCaveatsForReverse on a ReverseQueryOptions
func WithSkipCaveatsForReverse(skipCaveatsForReverse bool) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.SkipCaveatsForReverse = skipCaveatsForReverse
	}
}

// WithSkipExpirationForReverse returns an option that can set SkipExpirationForReverse on a ReverseQueryOptions
func WithSkipExpirationForReverse(skipExpirationForReverse bool) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.SkipExpirationForReverse = skipExpirationForReverse
	}
}

// WithSQLExplainCallbackForTestForReverse returns an option that can set SQLExplainCallbackForTestForReverse on a ReverseQueryOptions
func WithSQLExplainCallbackForTestForReverse(sQLExplainCallbackForTestForReverse SQLExplainCallbackForTest) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.SQLExplainCallbackForTestForReverse = sQLExplainCallbackForTestForReverse
	}
}

// WithQueryShapeForReverse returns an option that can set QueryShapeForReverse on a ReverseQueryOptions
func WithQueryShapeForReverse(queryShapeForReverse queryshape.Shape) ReverseQueryOptionsOption {
	return func(r *ReverseQueryOptions) {
		r.QueryShapeForReverse = queryShapeForReverse
	}
}

type RWTOptionsOption func(r *RWTOptions)

// NewRWTOptionsWithOptions creates a new RWTOptions with the passed in options set
func NewRWTOptionsWithOptions(opts ...RWTOptionsOption) *RWTOptions {
	r := &RWTOptions{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// NewRWTOptionsWithOptionsAndDefaults creates a new RWTOptions with the passed in options set starting from the defaults
func NewRWTOptionsWithOptionsAndDefaults(opts ...RWTOptionsOption) *RWTOptions {
	r := &RWTOptions{}
	defaults.MustSet(r)
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// ToOption returns a new RWTOptionsOption that sets the values from the passed in RWTOptions
func (r *RWTOptions) ToOption() RWTOptionsOption {
	return func(to *RWTOptions) {
		to.DisableRetries = r.DisableRetries
		to.Metadata = r.Metadata
		to.IncludesExpiredAt = r.IncludesExpiredAt
	}
}

// DebugMap returns a map form of RWTOptions for debugging
func (r *RWTOptions) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["DisableRetries"] = r.DisableRetries
	if r.Metadata == nil {
		debugMap["Metadata"] = "nil"
	} else if dm, ok := any(r.Metadata).(interface {
		DebugMap() map[string]any
	}); ok {
		debugMap["Metadata"] = dm.DebugMap()
	} else {
		debugMap["Metadata"] = *r.Metadata
	}
	debugMap["IncludesExpiredAt"] = r.IncludesExpiredAt
	return debugMap
}

// FlatDebugMap returns a flattened map form of RWTOptions for debugging
// Nested maps are flattened using dot notation (e.g., "parent.child.field")
func (r *RWTOptions) FlatDebugMap() map[string]any {
	var flatten func(m map[string]any) map[string]any
	flatten = func(m map[string]any) map[string]any {
		result := make(map[string]any, len(m))
		for key, value := range m {
			childMap, ok := value.(map[string]any)
			if ok {
				for childKey, childValue := range flatten(childMap) {
					result[key+"."+childKey] = childValue
				}
				continue
			}
			result[key] = value
		}
		return result
	}
	return flatten(r.DebugMap())
}

// RWTOptionsWithOptions configures an existing RWTOptions with the passed in options set
func RWTOptionsWithOptions(r *RWTOptions, opts ...RWTOptionsOption) *RWTOptions {
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithOptions configures the receiver RWTOptions with the passed in options set
func (r *RWTOptions) WithOptions(opts ...RWTOptionsOption) *RWTOptions {
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// WithDisableRetries returns an option that can set DisableRetries on a RWTOptions
func WithDisableRetries(disableRetries bool) RWTOptionsOption {
	return func(r *RWTOptions) {
		r.DisableRetries = disableRetries
	}
}

// WithMetadata returns an option that can set Metadata on a RWTOptions
func WithMetadata(metadata *structpb.Struct) RWTOptionsOption {
	return func(r *RWTOptions) {
		r.Metadata = metadata
	}
}

// WithIncludesExpiredAt returns an option that can set IncludesExpiredAt on a RWTOptions
func WithIncludesExpiredAt(includesExpiredAt bool) RWTOptionsOption {
	return func(r *RWTOptions) {
		r.IncludesExpiredAt = includesExpiredAt
	}
}
