package datastore

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/log"
	"github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/network"
	"github.com/testcontainers/testcontainers-go/wait"

	pgmigrations "github.com/authzed/spicedb/internal/datastore/postgres/migrations"
	"github.com/authzed/spicedb/pkg/datastore"
	"github.com/authzed/spicedb/pkg/migrate"
	"github.com/authzed/spicedb/pkg/secrets"
)

const (
	// NOTE: this is used in this file but also duplicated in postgres.conf.
	PostgresTestMaxConnections = "3000"
	PgTestPass                 = "testpass"
	PgTestUser                 = "testuser"
)

type postgresTester struct {
	targetMigration string
	pgbouncerProxy  *postgres.PostgresContainer
	pgContainer     *postgres.PostgresContainer
}

// RunPostgresForTesting returns a RunningEngineForTest for postgres
func RunPostgresForTesting(t testing.TB, targetMigration string, pgVersion string, enablePgbouncer bool) RunningEngineForTest {
	return RunPostgresForTestingWithCommitTimestamps(t, targetMigration, true, pgVersion, enablePgbouncer)
}

func RunPostgresForTestingWithCommitTimestamps(t testing.TB, targetMigration string, withCommitTimestamps bool, pgVersion string, enablePgbouncer bool) RunningEngineForTest {
	t.Helper()

	builder := &postgresTester{
		targetMigration: targetMigration,
	}

	if enablePgbouncer {
		// if we are running with pgbouncer enabled then set it up
		builder.runPgbouncerForTesting(t, pgVersion, withCommitTimestamps)
	} else {
		builder.runPostgresForTesting(t, pgVersion, withCommitTimestamps)
	}

	return builder
}

func (b *postgresTester) NewDatabase(t testing.TB) string {
	uniquePortion, err := secrets.TokenHex(4)
	require.NoError(t, err)

	newDBName := "db" + uniquePortion

	ctx := t.Context()
	conn := b.initializeHostConnection(t)
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, "CREATE DATABASE "+newDBName)
	require.NoError(t, err)

	row := conn.QueryRow(ctx, "SELECT datname FROM pg_catalog.pg_database WHERE datname = $1", newDBName)
	var dbName string
	err = row.Scan(&dbName)
	require.NoError(t, err)
	require.Equal(t, newDBName, dbName)

	connUri, err := b.pgContainer.ConnectionString(ctx, "sslmode=disable")
	require.NoError(t, err)

	return connUri
}

func (b *postgresTester) NewDatastore(t testing.TB, initFunc InitFunc) datastore.Datastore {
	t.Helper()
	ctx := context.WithValue(t.Context(), migrate.BackfillBatchSize, uint64(1000))

	var uri string

	require.EventuallyWithT(t, func(collect *assert.CollectT) {
		connectStr := b.NewDatabase(t)
		migrationDriver, err := pgmigrations.NewAlembicPostgresDriver(ctx, connectStr, datastore.NoCredentialsProvider, false)
		if assert.NoError(collect, err) {
			assert.NoError(collect, pgmigrations.DatabaseMigrations.Run(ctx, migrationDriver, b.targetMigration, migrate.LiveRun))
		}
		defer func() {
			migrationDriver.Close(ctx)
		}()
	}, 5*time.Second, 500*time.Millisecond)

	return initFunc("postgres", uri)
}

// runPgbouncerForTesting stands up the network, the postgres container, and the pgbouncer container
// for a test run.
func (b *postgresTester) runPgbouncerForTesting(t testing.TB, pgVersion string, withCommitTimestamps bool) {
	t.Helper()
	ctx := t.Context()

	// set up the network
	testNetwork, err := network.New(ctx)
	require.NoError(t, err)
	testcontainers.CleanupNetwork(t, testNetwork)

	// set up the pg container
	configFile := "./config/postgres.conf"
	if withCommitTimestamps {
		configFile = "./config/postgres-with-timestamps.conf"
	}

	image := fmt.Sprintf("mirror.gcr.io/library/postgres:%s", pgVersion)
	pgContainer, err := postgres.Run(ctx, image,
		testcontainers.WithEnv(map[string]string{
			// use md5 auth to align postgres and pgbouncer auth methods
			"POSTGRES_HOST_AUTH_METHOD": "md5",
			"POSTGRES_INITDB_ARGS":      "--auth=md5",
		}),
		// contains the config for commit timestamps and max conns
		postgres.WithConfigFile(configFile),
		network.WithNetwork([]string{"postgres"}, testNetwork),
		postgres.BasicWaitStrategies(),
	)
	testcontainers.CleanupContainer(t, pgContainer)
	b.pgContainer = pgContainer

	pgConnUri, err := pgContainer.ConnectionString(ctx)
	require.NoError(t, err)

	// set up the bouncer container
	bouncerContainer, err := postgres.Run(ctx, "mirror.gcr.io/edoburu/pgbouncer:latest",
		testcontainers.WithLogger(log.TestLogger(t)),
		testcontainers.WithEnv(map[string]string{
			"DATABASE_URL":    pgConnUri,
			"DB_NAME":         "*", // Needed to make pgbouncer okay with the randomly named databases generated by the test suite
			"DB_PASSWORD":     PgTestPass,
			"DB_USER":         PgTestUser,
			"AUTH_TYPE":       "md5", // use the same auth type as postgres
			"MAX_CLIENT_CONN": PostgresTestMaxConnections,
		}),
		// TODO: these may need to change based on logs. see what this container actually logs.
		postgres.BasicWaitStrategies(),
	)
	require.NoError(t, err)
	testcontainers.CleanupContainer(t, bouncerContainer)

	require.NoError(t, err)
	b.pgbouncerProxy = bouncerContainer
}

func (b *postgresTester) runPostgresForTesting(t testing.TB, pgVersion string, withCommitTimestamps bool) {
	t.Helper()
	ctx := t.Context()
	configFile := "./config/postgres.conf"
	if withCommitTimestamps {
		configFile = "./config/postgres-with-timestamps.conf"
	}

	image := fmt.Sprintf("mirror.gcr.io/library/postgres:%s", pgVersion)
	container, err := postgres.Run(ctx, image,
		// contains the config for commit timestamps and max conns
		postgres.WithConfigFile(configFile),
		postgres.WithUsername(PgTestUser),
		postgres.WithPassword(PgTestPass),
		postgres.BasicWaitStrategies(),
	)
	testcontainers.CleanupContainer(t, container)
	b.pgContainer = container
	require.NoError(t, err)
}

func (b *postgresTester) initializeHostConnection(t testing.TB) (conn *pgx.Conn) {
	t.Helper()
	ctx := t.Context()

	uri, err := b.pgContainer.ConnectionString(ctx, "sslmode=disable")
	require.NoError(t, err)

	if b.pgbouncerProxy != nil {
		uri, err = b.pgbouncerProxy.ConnectionString(ctx, "sslmode=disable")
		require.NoError(t, err)
	}

	conn, err = pgx.Connect(ctx, uri)
	require.NoError(t, err)

	return conn
}

type pgBouncerWaitStrategy struct {
	pollInterval   time.Duration
	startupTimeout time.Duration
}

var _ wait.Strategy = (*pgBouncerWaitStrategy)(nil)

func (p *pgBouncerWaitStrategy) WaitUntilReady(ctx context.Context, target wait.StrategyTarget) error {
	for {
		select {
		case <-ctx.Done():
			return fmt.Errorf("container not ready within the timeout: %w", ctx.Err())
		case <-time.After(500 * time.Millisecond):
		}
	}
}
