package datastore

import (
	"context"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/network"
	"github.com/testcontainers/testcontainers-go/wait"

	pgmigrations "github.com/authzed/spicedb/internal/datastore/postgres/migrations"
	"github.com/authzed/spicedb/pkg/datastore"
	"github.com/authzed/spicedb/pkg/migrate"
	"github.com/authzed/spicedb/pkg/secrets"
)

const (
	// NOTE: this is used in this file but also duplicated in postgres.conf.
	PostgresTestMaxConnections = "3000"
	PgbouncerTestPort = "6432"
)

type postgresTester struct {
	targetMigration      string
	pgbouncerProxy       *testcontainers.DockerContainer
	pgContainer          *postgres.PostgresContainer
}

// RunPostgresForTesting returns a RunningEngineForTest for postgres
func RunPostgresForTesting(t testing.TB, targetMigration string, pgVersion string, enablePgbouncer bool) RunningEngineForTest {
	return RunPostgresForTestingWithCommitTimestamps(t, targetMigration, true, pgVersion, enablePgbouncer)
}

func RunPostgresForTestingWithCommitTimestamps(t testing.TB, targetMigration string, withCommitTimestamps bool, pgVersion string, enablePgbouncer bool) RunningEngineForTest {
	t.Helper()

	builder := &postgresTester{
		targetMigration:      targetMigration,
	}

	if enablePgbouncer {
		// if we are running with pgbouncer enabled then set it up
		builder.runPgbouncerForTesting(t, pgVersion, withCommitTimestamps)
	} else {
		builder.runPostgresForTesting(t, pgVersion, withCommitTimestamps)
	}

	return builder
}

func (b *postgresTester) NewDatabase(t testing.TB) string {
	uniquePortion, err := secrets.TokenHex(4)
	require.NoError(t, err)

	newDBName := "db" + uniquePortion

	ctx := t.Context()
	conn := b.initializeHostConnection(t)
	defer conn.Close(ctx)

	_, err = conn.Exec(ctx, "CREATE DATABASE "+newDBName)
	require.NoError(t, err)

	row := conn.QueryRow(ctx, "SELECT datname FROM pg_catalog.pg_database WHERE datname = $1", newDBName)
	var dbName string
	err = row.Scan(&dbName)
	require.NoError(t, err)
	require.Equal(t, newDBName, dbName)

	connUri, err := b.pgContainer.ConnectionString(ctx, "sslmode=disable")
	require.NoError(t, err)

	return connUri
}

const (
	retryCount         = 4
	timeBetweenRetries = 1 * time.Second
)

func (b *postgresTester) NewDatastore(t testing.TB, initFunc InitFunc) datastore.Datastore {
	t.Helper()
	for i := 1; i <= retryCount; i++ {
		connectStr := b.NewDatabase(t)

		migrationDriver, err := pgmigrations.NewAlembicPostgresDriver(context.Background(), connectStr, datastore.NoCredentialsProvider, false)
		if err == nil {
			ctx := context.WithValue(context.Background(), migrate.BackfillBatchSize, uint64(1000))
			require.NoError(t, pgmigrations.DatabaseMigrations.Run(ctx, migrationDriver, b.targetMigration, migrate.LiveRun))
			return initFunc("postgres", connectStr)
		}
		defer func() {
			migrationDriver.Close(context.Background())
		}()

		if i == retryCount {
			require.NoError(t, err, "got error when trying to create migration driver")
		} else {
			t.Logf("failed to create migration driver: %v, retrying... %d", err, i)
		}

		time.Sleep(time.Duration(i) * timeBetweenRetries)
	}

	require.Fail(t, "failed to create datastore for testing")
	return nil
}

// runPgbouncerForTesting stands up the network, the postgres container, and the pgbouncer container
// for a test run.
func (b *postgresTester) runPgbouncerForTesting(t testing.TB, pgVersion string, withCommitTimestamps bool) {
	t.Helper()
	ctx := t.Context()
	
	// set up the network
	testNetwork, err := network.New(ctx)
	require.NoError(t, err)
	testcontainers.CleanupNetwork(t, testNetwork)

	// set up the pg container
	configFile := "./config/postgres.conf"
	if withCommitTimestamps {
		configFile = "./config/postgres-with-timestamps.conf"
	}

	image := fmt.Sprintf("mirror.gcr.io/library/postgres:%s", pgVersion)
		pgContainer, err := postgres.Run(ctx, image,
		testcontainers.WithEnv(map[string]string{
			// use md5 auth to align postgres and pgbouncer auth methods
			"POSTGRES_HOST_AUTH_METHOD": "md5",
			"POSTGRES_INITDB_ARGS":      "--auth=md5",
		}),
		// contains the config for commit timestamps and max conns
		postgres.WithConfigFile(configFile),
		network.WithNetwork([]string{"postgres"}, testNetwork),
		postgres.BasicWaitStrategies(),
	)
	testcontainers.CleanupContainer(t, pgContainer)
	b.pgContainer = pgContainer

	pgConnUri, err := pgContainer.ConnectionString(ctx)
	require.NoError(t, err)

	// set up the bouncer container
	bouncerContainer, err := testcontainers.Run(ctx, "mirror.gcr.io/edoburu/pgbouncer:latest",
	testcontainers.WithEnv(map[string]string{
		"DATABASE_URL": pgConnUri,
			"LISTEN_PORT":      PgbouncerTestPort,
			"DB_NAME":          "*",   // Needed to make pgbouncer okay with the randomly named databases generated by the test suite
			"AUTH_TYPE":        "md5", // use the same auth type as postgres
			"MAX_CLIENT_CONN":  PostgresTestMaxConnections,
		}),
		testcontainers.WithExposedPorts(PgbouncerTestPort),
		testcontainers.WithWaitStrategy(wait.ForListeningPort(PgbouncerTestPort + "/tcp").
			WithStartupTimeout(dockerBootTimeout)),
			network.WithNetwork([]string{"pgbouncer"}, testNetwork),
)
	require.NoError(t, err)
	testcontainers.CleanupContainer(t, bouncerContainer)

	require.NoError(t, err)
	b.pgbouncerProxy = bouncerContainer
}

func (b *postgresTester) runPostgresForTesting(t testing.TB, pgVersion string, withCommitTimestamps bool) {
	t.Helper()
	ctx := t.Context()
	configFile := "./config/postgres.conf"
	if withCommitTimestamps {
		configFile = "./config/postgres-with-timestamps.conf"
	}

	image := fmt.Sprintf("mirror.gcr.io/library/postgres:%s", pgVersion)
		container, err := postgres.Run(ctx, image,
		// contains the config for commit timestamps and max conns
		postgres.WithConfigFile(configFile),
		postgres.BasicWaitStrategies(),
	)
	testcontainers.CleanupContainer(t, container)
	b.pgContainer = container
	require.NoError(t, err)
}

func (b *postgresTester) initializeHostConnection(t testing.TB) (conn *pgx.Conn) {
	t.Helper()
	ctx := t.Context()

	uri, err := b.pgContainer.ConnectionString(ctx, "sslmode=disable")
	require.NoError(t, err)

	if b.pgbouncerProxy != nil {
		// we have a pgbouncer instance; we want to use its port on the host so we
		// find-and-replace the postgres port with the pgbouncer port
		bouncerEndpoint, err := b.pgbouncerProxy.PortEndpoint(ctx, PgbouncerTestPort, "")
		require.NoError(t, err)
		
		// do something similar for the pg port
		// get the endpoint (hostname:port) for the pg container
		pgEndpoint, err := b.pgContainer.PortEndpoint(ctx, "5432/tcp", "")
		require.NoError(t, err)

		strings.Replace(uri, pgEndpoint, bouncerEndpoint, 1)
	}

	conn, err = pgx.Connect(ctx, uri)
	require.NoError(t, err)

	return conn
}

type pgBouncerWaitStrategy struct {
	pollInterval time.Duration
	startupTimeout time.Duration
}
var _ wait.Strategy = (*pgBouncerWaitStrategy)(nil)


func (p *pgBouncerWaitStrategy) WaitUntilReady(ctx context.Context, target wait.StrategyTarget) error {
	for {
		select {
		case <-ctx.Done():
			return fmt.Errorf("container not ready within the timeout: %w", ctx.Err())
		case <-time.After(500 * time.Millisecond):
		}
	}
}
