{
 "title": "SpiceDB Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "p99 Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"spicedb\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"spicedb\"}[$__rate_interval])) by (grpc_service, grpc_method)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "description": "Response codes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_method, grpc_code) (increase(grpc_server_handled_total{grpc_service=~\".*PermissionsService|.*SchemaService|.*ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}} ({{grpc_code}})"
    }
   ]
  },
  { "title": "Datastore Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "p99 Latency by Datastore Operation",
   "type": "timeseries",
   "description": "Datastore query latency",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(spicedb_datastore_query_latency_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RPS by Datastore Operation",
   "type": "timeseries",
   "description": "Datastore queries per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(spicedb_datastore_query_latency_count[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Max time spent acquiring connections",
   "type": "timeseries",
   "description": "Time spent acquiring datastore connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (rate(pgxpool_acquire_duration_ns{job=\"spicedb\",pool_usage=~\"read|write\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "The number of goroutines reported by the Go runtime.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"spicedb\"}",
     "legendFormat": "Goroutines ({{instance}})"
    },
    {
     "expr": "irate(go_goroutines{job=\"spicedb\"}[$__rate_interval])",
     "legendFormat": "Goroutine Derivative ({{instance}})"
    }
   ]
  },
  {
   "title": "GC (garbage collection)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, instance) (rate(go_sched_pauses_total_gc_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99 of duration ({{instance}})"
    },
    {
     "expr": "go_gc_cycles_total_gc_cycles_total",
     "legendFormat": "count ({{instance}})"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"spicedb\"}",
     "legendFormat": "Heap In Use ({{instance}})"
    },
    {
     "expr": "go_gc_gomemlimit_bytes{job=\"spicedb\"}",
     "legendFormat": "GOMEMLIMIT ({{instance}})"
    },
    {
     "expr": "spicedb_memory_middleware_memory_usage_percent{job=\"spicedb\"}",
     "legendFormat": "Usage % ({{instance}})"
    }
   ]
  },
  {
   "title": "Memory Allocation Rate (malloc/sec)",
   "type": "timeseries",
   "description": "The number of heap allocations (mallocs) as a rate (malloc/sec).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"spicedb\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mutex wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_sync_mutex_wait_total_seconds_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Allocation Rate",
   "type": "timeseries",
   "description": "Shows the number of heap allocations (as a byte/sec rate).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"spicedb\"}[$__rate_interval])",
     "legendFormat": "bytes/sec ({{instance}}"
    }
   ]
  }
 ]
}