# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: "Lint"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
  merge_group:
    types:
      - "checks_requested"
permissions:
  contents: "read"
concurrency:
  group: "spicedb-lint-${{ github.event.pull_request.number }}"
  cancel-in-progress: true
jobs:
  go-license-check:
    name: "License Check"
    runs-on: "depot-ubuntu-24.04-small"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "authzed/actions/setup-go@main"
      - name: "Check Licenses"
        uses: "authzed/actions/go-license-check@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
        with:
          ignore: "buf.build" # Has no license information
  ensure-docs-uptodate:
    name: "Ensure Docs are up to date"
    runs-on: "depot-ubuntu-24.04-4"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "authzed/actions/setup-go@main"
      - name: "Generate docs"
        run: "go run mage.go gen:docs"
      - uses: "chainguard-dev/actions/nodiff@c69a264ec2a5934c3186c618f368fc1c86f16cff" # main
        with:
          path: ""
          fixup-command: "mage gen:docs"
  lint-everything:
    name: "Lint Everything"
    runs-on: "depot-ubuntu-24.04-4"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "authzed/actions/setup-go@main"
      - name: "Lint Everything"
        run: "go run mage.go lint:all"
      - uses: "chainguard-dev/actions/nodiff@c69a264ec2a5934c3186c618f368fc1c86f16cff" # main
        with:
          path: ""
          fixup-command: "go run mage.go lint:all"
