# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: "Devel (nightly) Release"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
permissions:
  contents: "read"
jobs:
  goreleaser:
    runs-on: "depot-ubuntu-24.04-4"
    permissions:
      contents: "write"
      packages: "write" # publish to GHCR
    steps:
      - uses: "actions/checkout@v7"
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@main"
      - name: "Install snapcraft"
        run: |
          sudo snap install snapcraft --channel=8.x/stable --classic
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      - uses: "authzed/actions/docker-login@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8" # v4.2.0
      - uses: "docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c" # v4.2.0
      - uses: "goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94" # v7.2.3
        with:
          distribution: "goreleaser-pro"
          version: "2.15.2"
          args: "release -f .goreleaser.nightly.yml --clean --nightly"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
