# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: "Release for Windows"
on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
permissions:
  contents: "read"
jobs:
  release-windows:
    runs-on: "windows-latest"
    permissions:
      contents: "write"
      packages: "write" # publish to GHCR
    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@main"
      - uses: "nowsprinting/check-version-format-action@976544c127ab571b88419766cc9d3b459f8d7b82" # v5.0.1
        id: "version"
        with:
          prefix: "v"
      - uses: "authzed/actions/docker-login@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29" # v7.0.0
        with:
          distribution: "goreleaser-pro"
          # NOTE: keep in sync with goreleaser version in other job.
          # github actions don't allow yaml anchors.
          version: "v2.15.2"
          args: "release --clean --config=.goreleaser.windows.yml"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
          CHOCOLATEY_API_KEY: "${{ secrets.CHOCOLATEY_API_KEY }}"
      - name: "Notify Slack if failure"
        if: "failure()"
        uses: "slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95" # v3.0.1
        with:
          webhook: "${{ secrets.SLACK_WEBHOOK_URL }}"
          webhook-type: "incoming-webhook"
          payload: |
            text: "*SpiceDB Release for Windows Failed!*
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    :x: @eng-oss *SpiceDB Release for Windows Failed*. Please take a look.
                    *Repository:* <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
                    *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
                    *Job Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Job Run>
                    *Actor:* ${{ github.actor }}
                    *Ref:* ${{ github.ref }}
                    *Workflow:* ${{ github.workflow }}
